/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nnproject_installerext_InstallerExtension_93 */

#ifndef _Included_ru_nnproject_installerext_InstallerExtension_93
#define _Included_ru_nnproject_installerext_InstallerExtension_93
#ifdef __cplusplus
extern "C" {
#endif
#undef ru_nnproject_installerext_InstallerExtension_93_VERSION
#define ru_nnproject_installerext_InstallerExtension_93_VERSION 1L
/*
 * Class:     ru_nnproject_installerext_InstallerExtension_93
 * Method:    _getUid
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_installerext_InstallerExtension_193__1getUid
  (JNIEnv *, jclass, jstring, jstring, jintArray);

/*
 * Class:     ru_nnproject_installerext_InstallerExtension_93
 * Method:    _isInstalled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_nnproject_installerext_InstallerExtension_193__1isInstalled
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_nnproject_installerext_InstallerExtension_93
 * Method:    _getInstalledVersion
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_installerext_InstallerExtension_193__1getInstalledVersion
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     ru_nnproject_installerext_InstallerExtension_93
 * Method:    _getInstalledSisVersion
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_installerext_InstallerExtension_193__1getInstalledSisVersion
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     ru_nnproject_installerext_InstallerExtension_93
 * Method:    _launchApp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_installerext_InstallerExtension_193__1launchApp
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
